# Module 4

## Numpy

NumPy, short for Numerical Python, is one of the most important foundational packages for numerical computing in Python. 

NumPy provides: 

- `ndarray`, an efficient multidimensional array providing fast array-oriented arithmetic operations and flexible broadcasting capabilities
- Mathematical functions for fast operations on entire arrays of data without having to write loops
- Tools for reading/writing array data to disk and working with memory-mapped files
- Linear algebra and random number generation capabilities

For R users, `ndarray` is similar to an R vector or matrix (R vectors are built-in, unlike Python, which requires the NumPy library for such objects).

In future lectures, we will cover the Pandas library, which gives functionality similar to R's `data.frame` and tidyverse packages such as `dplyr`.

### Import conventions

NumPy is conventionally imported as:

In [2]:
import numpy as np

Then, functions in NumPy can be used as `np.array`. This prevents confusion for functions with the same name from different modules. For example, there is a built-in `max` function in Python, which is different from the NumPy `np.max` function.

### ndarray

One of the key features of NumPy is its N-dimensional array object, or ndarray, which is a fast, flexible container for large datasets in Python. Arrays enable you to perform mathematical operations on whole blocks of data using similar syntax to the equivalent operations between scalar elements.

An ndarray is a generic multidimensional container where all elements must be of the same type (e.g. `float64`). Every array has a shape, which is a tuple indicating the size of each dimension, and a dtype, which is an object describing the data type of the array.

In [4]:
new_array = np.ones((10,10))
print(new_array.shape)
#tuple with two dimensions of this array 
print(new_array.dtype)
type(new_array)

(10, 10)
float64


numpy.ndarray

### Create arrays

In [5]:
np.ones, np.ones_like, np.zeros, np.eye, np.arange, np.linspace, np.logspace

(<function numpy.ones(shape, dtype=None, order='C', *, device=None, like=None)>,
 <function ones_like at 0x00000201C879B270>,
 <function numpy.zeros(shape, dtype=None, order='C', *, device=None, like=None)>,
 <function numpy.eye(N, M=None, k=0, dtype=<class 'float'>, order='C', *, device=None, like=None)>,
 <function numpy.arange(start_or_stop, /, stop=None, step=1, *, dtype=None, device=None, like=None)>,
 <function linspace at 0x00000201C87BE5B0>,
 <function logspace at 0x00000201C87BE770>)

```{.python}
help(np.ones)
```

In [6]:
np.ones(3)

array([1., 1., 1.])

In [131]:
np.ones(3).shape

(3,)

In [132]:
np.zeros(4)

array([0., 0., 0., 0.])

In [7]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [134]:
np.eye(4).shape

(4, 4)

In [135]:
np.zeros_like(np.eye(4))


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [136]:
np.zeros_like(np.eye(4)).shape


(4, 4)

In [137]:
np.ones_like(np.eye(4))


array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [138]:
np.arange(7)

array([0, 1, 2, 3, 4, 5, 6])

In [139]:
np.linspace(4, 8, num=9)

array([4. , 4.5, 5. , 5.5, 6. , 6.5, 7. , 7.5, 8. ])

In [140]:
np.logspace(0, 2, num=3)

array([  1.,  10., 100.])

### Specify entries manually

You can input a list to `np.array` to create a 1-dimensional ndarray.

In [141]:
np.array([1.0, 2.0, 3.3])

array([1. , 2. , 3.3])

For a 2-dimensional ndarray, you can iput a list of lists. The first row will be the first list, and so on:

In [8]:
A = np.array([[1.0, 2.0, 3.0],
          [1.1, 2.2, 3.3]])
A

#every entry of outer list defines row in array 
print(A)

[[1.  2.  3. ]
 [1.1 2.2 3.3]]


In [5]:
A.shape

(2, 3)

### Changing dtype

Some NumPy data types are given [here](https://wesmckinney.com/book/numpy-basics#tbl-table_array_dtypes).

In [ ]:
o = np.ones(3, dtype=np.int8)


In [145]:
o.dtype


dtype('int8')

In [ ]:
o = o.astype(float)

#change type of variable from float to integer 

### Random numbers

#### Old way

This is the old version of how to generate random samples with numpy; it is still commonly used. 

In Python, random numbers are generated using algorithms. That is, they are not truly random - we call them pseudo-random.

##### Setting the seed
Before generating random samples, it is recommended to set the "seed". The seed essentially is an initial value for the random number generator. You can close your file, reopen it again another day, and if you set the seed to the same value, you will get the same random samples. This helps make code reproducible. 

If you do not set a seed, `np.random` will get the seed from the computer's operating system and it will be a function of the date/time. Because you will never run your code at the exact same time again, the output will be different every time you run it. 

Here's a nice intro to pseudo-random number generation [(link)](https://www.pcg-random.org/rng-basics.html)

In [147]:
np.random.seed(42) # Set the seed to 42

In [148]:
np.random.uniform(size=(3, 4))

array([[0.37454012, 0.95071431, 0.73199394, 0.59865848],
       [0.15601864, 0.15599452, 0.05808361, 0.86617615],
       [0.60111501, 0.70807258, 0.02058449, 0.96990985]])

If you run the above two commands again, you can see that the random uniform samples are the same.

In [149]:
np.random.uniform(size=(3, 4))

array([[0.83244264, 0.21233911, 0.18182497, 0.18340451],
       [0.30424224, 0.52475643, 0.43194502, 0.29122914],
       [0.61185289, 0.13949386, 0.29214465, 0.36636184]])

Running `np.random.uniform(size=(3, 4))` a second time will generate a different set of uniform samples. 

You can think of this as - the random number generator has moved one step forward in the algorithm from the initial state (specified by seed=42). This is good - we don't want the same numbers to be sampled! 

Typically, we set the seed once at the beginning of the file. Then, if we run the `np.random.` commands in the same order, we will always get the same output. 

In [150]:
np.random.normal(size=(3, 4))

array([[ 1.46564877, -0.2257763 ,  0.0675282 , -1.42474819],
       [-0.54438272,  0.11092259, -1.15099358,  0.37569802],
       [-0.60063869, -0.29169375, -0.60170661,  1.85227818]])

#### New way

The new way to generate random samples in numpy is to first define a Generator. If you do not set a seed, the command is:


In [ ]:
rng = np.random.default_rng() # don't set seed; seed taken from operating system state

#create an object that comes from np library 
#you let the operator decide that seed 

To set the seed, add the seed argument:

In [6]:
rng = np.random.default_rng(seed=42) # setting seed to 42

Then, use `rng` as you would `np.random` from before.

In [153]:
rng.uniform(size=(1,2))

array([[0.77395605, 0.43887844]])

In [154]:
rng.standard_normal(size=(2,1))

array([[0.7504512 ],
       [0.94056472]])

In [ ]:
rng.normal(loc=10,scale=3, size=(1,2))

#mean of 10 and standard deviation of 3

array([[4.14689443, 6.09346148]])

In [ ]:
rng.normal(loc=np.array([3,4]), scale = 0.05)

#mean of 3 and 4 and standard deviation of 0.05

array([3.00639202, 3.98418787])

You can see all available distributions to sample from using:
```{.python}
help(rng)
```

### Accessing single entries

Python is zero-index based (entries start at [0,0] instead of [1,1] like R)

In [157]:
o = np.ones(3)

In [158]:
o[0]

np.float64(1.0)

In [159]:
o[1]

np.float64(1.0)

In [9]:
A 

array([[1. , 2. , 3. ],
       [1.1, 2.2, 3.3]])

In [10]:
A[0, 0]


np.float64(1.0)

In [11]:
A[1, 2]


np.float64(3.3)

### Accessing arrays with slices

Note: Python uses row-major ordering (unlike R, which does column-major ordering)

[Helpful notes on R vs. Python](https://cran.r-project.org/web/packages/reticulate/vignettes/arrays.html)

In [7]:
B = np.arange(24).reshape((4, 6))
B

#one dimensional array with 24 numbers 
#reshape from one dimension to two dimensions with 4 rows and 6 columns
#now 4 x 6 array 
#first fills in rows 

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [164]:
B.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [8]:
#often called slicing 

# The two middle rows:
B[1:3, :]

# The two middle rows, only second column
B[1:3, 1]

# Use two columns (two ":") to skip some integers periodically
B

B[:, 0:7:2] # keep every other column

B[:, ::2] # keep every other column

B[:, 0:7:3] # keep one in three columns


array([[ 0,  3],
       [ 6,  9],
       [12, 15],
       [18, 21]])

In [166]:
arr = np.zeros((8, 4))

for i in range(8):
    arr[i] = i

arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [167]:
arr[[4, 3, 0, 6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [168]:
arr = np.arange(32).reshape((8, 4))

In [169]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]] # this gets indicies (1, 0), (5, 3), (7, 1), (2, 2)

array([ 4, 23, 29, 10])

### Comparing arrays
The `tol` (precision under which two numbers will be considered equal) can be modified, see the `rtol` and `atol` argument [here](https://numpy.org/doc/stable/reference/generated/numpy.isclose.html).

In [170]:

np.isclose, np.allclose # these functions help to compare floats arrays for equality.

np.isclose(np.exp(-20), 0.)

np.exp(-3000) == 0

np.exp(20) == 0



np.False_

### Operations along axis

`B.sum(axis=0)` means to sum over dimension 0 (rows). 

In [ ]:
np.sum, np.mean

B

B.sum()
#sum of all entires 
B.sum(axis=0)
#number of outputs is equal to number of rows 
np.sum(B, axis=0)

np.mean(B, axis=1)

array([ 2.5,  8.5, 14.5, 20.5])

### Adding, multiplying arrays componentwise



In [ ]:
C = np.ones_like(B)

C

B

B + C

B + 3*C
#entry wise mulitplication 


array([[ 3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26]])

### Componentwise multiplication (this is not the matrix product)



In [173]:
C * B


array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

### Other element-wise operations

In [ ]:
B = np.arange(24).reshape((4, 6))
print(B)
np.sqrt(B)

array([[0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
        2.23606798],
       [2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
        3.31662479],
       [3.46410162, 3.60555128, 3.74165739, 3.87298335, 4.        ,
        4.12310563],
       [4.24264069, 4.35889894, 4.47213595, 4.58257569, 4.69041576,
        4.79583152]])

In [175]:
np.maximum(B, 10 * rng.normal(size=B.shape))

array([[ 0.        ,  1.        ,  8.79397975,  7.77791935,  4.        ,
        11.27241207],
       [ 6.        ,  7.        ,  8.        ,  9.        , 10.        ,
        11.        ],
       [12.        , 13.        , 14.        , 15.        , 16.        ,
        17.        ],
       [18.        , 19.        , 20.        , 21.        , 22.        ,
        23.        ]])

### Some array methods

In [176]:
B.max()

np.int64(23)

In [177]:
B.max(axis=0)

array([18, 19, 20, 21, 22, 23])

In [ ]:
B.std()
B.std(axis=1)
#standard deviation by column 

np.float64(6.922186552431729)

In [179]:
B.var()

np.float64(47.916666666666664)

In [180]:
c = rng.normal(size=(10))

In [181]:
c

array([-0.51224273, -0.81377273,  0.61597942,  1.12897229, -0.11394746,
       -0.84015648, -0.82448122,  0.65059279,  0.74325417,  0.54315427])

In [182]:
c.argmax()

np.int64(3)

In [183]:
# NumPy arrays can be sorted in place with the sort method:
c.sort()

In [184]:
d = rng.normal(size=(10))
d

array([-0.66550971,  0.23216132,  0.11668581,  0.2186886 ,  0.87142878,
        0.22359555,  0.67891356,  0.06757907,  0.2891194 ,  0.63128823])

In [185]:
np.sort(d) # this returns a sorted copy of d

array([-0.66550971,  0.06757907,  0.11668581,  0.2186886 ,  0.22359555,
        0.23216132,  0.2891194 ,  0.63128823,  0.67891356,  0.87142878])

### Matrix product

In [ ]:
# C @ B # fails because C is (4, 6) and B is (4, 6)

C @ B.T # (4, 6) , (6, 4) = (4, 4)

B.T @ C # (6, 4) , (4, 6) = (6, 6)

#.T transpose matrix 


array([[36, 36, 36, 36, 36, 36],
       [40, 40, 40, 40, 40, 40],
       [44, 44, 44, 44, 44, 44],
       [48, 48, 48, 48, 48, 48],
       [52, 52, 52, 52, 52, 52],
       [56, 56, 56, 56, 56, 56]])

### Shape

In [187]:
np.transpose, np.newaxis, np.expand_dims, np.reshape, np.swapaxes, np.moveaxis

(<function transpose at 0x7c97b4f41df0>,
 None,
 <function expand_dims at 0x7c979ff02570>,
 <function reshape at 0x7c97b4f414f0>,
 <function swapaxes at 0x7c97b4f41c30>,
 <function moveaxis at 0x7c97b4f60770>)

In [188]:
B.shape

B.T

B.T.shape

B[np.newaxis, :, :].shape

B[:, :, np.newaxis].shape

B[:, np.newaxis, :].shape

(4, 1, 6)

### Concatenate, stacking arrays

In [189]:
np.stack, np.vstack, np.hstack, np.column_stack


A = rng.normal(size=(2, 3))
AA= rng.normal(size=(2, 3))
B = rng.normal(size=(2, 2))
C = rng.normal(size=(3, 3))



The following concatenation/stacking operations are allowed to stack by creating a new axis

In [190]:
np.stack([A, AA])

array([[[-1.45715582, -0.31967122, -0.47037265],
        [-0.63887785, -0.27514225,  1.49494131]],

       [[-0.86583112,  0.96827835, -1.68286977],
        [-0.33488503,  0.16275307,  0.58622233]]])

In [191]:
np.stack([A, AA]).shape

(2, 2, 3)

In [192]:
print(np.stack([A, AA, A, AA]).shape)
np.stack([A, AA, A, AA])

(4, 2, 3)


array([[[-1.45715582, -0.31967122, -0.47037265],
        [-0.63887785, -0.27514225,  1.49494131]],

       [[-0.86583112,  0.96827835, -1.68286977],
        [-0.33488503,  0.16275307,  0.58622233]],

       [[-1.45715582, -0.31967122, -0.47037265],
        [-0.63887785, -0.27514225,  1.49494131]],

       [[-0.86583112,  0.96827835, -1.68286977],
        [-0.33488503,  0.16275307,  0.58622233]]])

In [193]:
# the first index of the newly created axis (first new axis) contais A
# the second index of the newly created axis (first new axis) contais AA
assert np.allclose(np.stack([A, AA])[0], A)
assert np.allclose(np.stack([A, AA])[1], AA)

In [194]:
np.stack([A, AA, A**2, 7*A]).shape

(4, 2, 3)

vertical stacking, without creating a new axis


In [195]:
np.vstack([A, AA]).shape

(4, 3)

In [196]:
np.vstack([A, AA])


array([[-1.45715582, -0.31967122, -0.47037265],
       [-0.63887785, -0.27514225,  1.49494131],
       [-0.86583112,  0.96827835, -1.68286977],
       [-0.33488503,  0.16275307,  0.58622233]])

In [197]:
np.stack([A, AA])

array([[[-1.45715582, -0.31967122, -0.47037265],
        [-0.63887785, -0.27514225,  1.49494131]],

       [[-0.86583112,  0.96827835, -1.68286977],
        [-0.33488503,  0.16275307,  0.58622233]]])

In [198]:
A.shape, C.shape


((2, 3), (3, 3))

In [199]:
np.vstack([A, C]).shape


(5, 3)

In [200]:
A.shape, B.shape


((2, 3), (2, 2))

In [201]:
# np.vstack([A, B]).shape # this fails


In [202]:
np.hstack([A, AA]).shape

(2, 6)

In [203]:
np.hstack([A, AA, B]).shape


(2, 8)

In [204]:
A.shape, C.shape


((2, 3), (3, 3))

In [205]:
# np.hstack([A, C]) # this fails

Concatenate lets us specify an axis along which to stack

In [206]:
A.shape, B.shape

((2, 3), (2, 2))

In [207]:
np.concatenate([A, B], axis=1).shape

(2, 5)

### Selecting columns or rows based on values/comparison


In [10]:
U = np.arange(24).reshape((4, 6))
U.shape

(4, 6)

In [13]:
U.sum(axis=1)

#summing going across the columns for each of the rows 


array([ 15,  51,  87, 123])

In [14]:
U.sum(axis=1) > 60


array([False, False,  True,  True])

In [211]:
# rows with row-sum at last 60
U[ U.sum(axis=1) > 60, :]

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [212]:
# Columns with a minimum element smaller or equal to 2
U[:, U.min(axis=0) <= 2]

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [12, 13, 14],
       [18, 19, 20]])

### Matrix multiplication, matrix inversion, matrix determinant


In [213]:
M = np.random.uniform(size=(2,2)).round(2) # a two-by-two matrix
M

array([[0.12, 0.5 ],
       [0.03, 0.91]])

In [214]:
# matrix transpose
M.T 


array([[0.12, 0.03],
       [0.5 , 0.91]])

In [215]:
M @ M # matrix product


array([[0.0294, 0.515 ],
       [0.0309, 0.8431]])

In [216]:
np.linalg.inv, np.linalg.det, np.linalg.matrix_rank, np.linalg.solve

(<function inv at 0x7c97b41626f0>,
 <function det at 0x7c97b4163b70>,
 <function matrix_rank at 0x7c97b41637b0>,
 <function solve at 0x7c97b41627f0>)

In [217]:
np.linalg.inv(M)

np.linalg.inv(M) @ M

np.allclose(np.linalg.inv(M) @ M, np.eye(2))

True

Matrix operations and 3+ dimensions: Stacks of matrix

A stack of three 2x2 matrices

In [218]:
MM = np.random.normal(size=(2, 2)).round(2)
MMM = np.random.normal(size=(2, 2)).round(2)
S = np.stack([M, MM, MM])
S

array([[[ 0.12,  0.5 ],
        [ 0.03,  0.91]],

       [[ 0.82, -1.22],
        [ 0.21, -1.96]],

       [[ 0.82, -1.22],
        [ 0.21, -1.96]]])

Matrix operations apply to a single matrix, or simultaneously to each matrix in the stack

In [219]:
np.linalg.det(M)

np.linalg.det(MM)

np.linalg.det(MMM)

np.linalg.det(S)

array([ 0.0942, -1.351 , -1.351 ])

In [220]:
np.linalg.inv(S)

array([[[ 9.66029724, -5.30785563],
        [-0.31847134,  1.27388535]],

       [[ 1.4507772 , -0.90303479],
        [ 0.15544041, -0.60695781]],

       [[ 1.4507772 , -0.90303479],
        [ 0.15544041, -0.60695781]]])

### Broadcasting: automatic expansion of arrays that do not have the same size

When operating on two arrays, NumPy compares their shapes element-wise. It starts with the trailing (i.e. rightmost) dimension and works its way left. Two dimensions are compatible when
- they are equal, or
- one of them is 1.

If these conditions are not met, a `ValueError: operands could not be broadcast together` exception is thrown, indicating that the arrays have incompatible shapes.

Broadcasting is then performed over the missing or length 1 dimensions.

numpy store homogenous arrays, store them and use them as if they were an array when you possibly have more than two dimensions
most conservative way is to build another matrix is the same values for each row that matches the original matrix 


broadcasting - what happesn why you try do matrix vs vector 
takes two arrays you are working with it takes the trailing dimension (most right array) tries to match trailing dimension from the right to the left, when there is no matching anymore it performs broadcasting 


Examples:

    A      (2d array):  5 x 4
    B      (1d array):      1
    Result (2d array):  5 x 4

    A      (2d array):  5 x 4
    B      (1d array):      4
    Result (2d array):  5 x 4

    A      (3d array):  15 x 3 x 5
    B      (3d array):  15 x 1 x 5
    Result (3d array):  15 x 3 x 5

    A      (3d array):  15 x 3 x 5
    B      (2d array):       3 x 5
    Result (3d array):  15 x 3 x 5

    A      (3d array):  15 x 3 x 5
    B      (2d array):       3 x 1
    Result (3d array):  15 x 3 x 5  

#### Broadcasting illustrations 

From Python for Data Analysis:

trailing dimension is 3 for right and left, left is a tuple 
numpy fills with the original array until it matches the dimension 

Row

standardization 
remove the mean, compute mean column by column, gives you 3 Dimension vector, have to substract mean from data vector, remove mean from every single column 

in R you use col means, R stores column wise, you 

<img src="https://wesmckinney.com/book/images/pda3_a004.png" width="400" />


Column

trailing dimension is 1 and 3, then moves on has a match with 4 and 4 
take dimension that is 1 until it matches dimension of the other array until you have arrays of the same dimension 


<img src="https://wesmckinney.com/book/images/pda3_a005.png" width="400" />



Array

3 dimensional array
trailing dimension, 2, 2, 2, 
4,4,4 match 
no match on 3, so numpy adds duplicates until it gets 3 

<img src="https://wesmckinney.com/book/images/pda3_a006.png" width="400" />

From NumPy docs:

<img src="https://numpy.org/doc/stable/_images/broadcasting_3.png" width="400" />


mismatch operations because trailing dimension is not matched 4 vs 3 
1 is an exception because you can always match 1 

In [3]:
V = np.arange(12).reshape(3, 4)
u3 = np.arange(3)*0.1   # vector size 3
u4 = np.arange(4)*0.01  # vector size 4
V

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
#V is my data matrix, i want to standardize it
V.mean(axis=0) #do this across the rows, loop over 0 dimension which is the rows, so we get mean for each column
V.mean(axis=0).shape

print(V.shape) 
print(V.mean(axis=0).shape)

#for loops tend to be slower 

#replicate vectors under the hood 

V_nomean =V-V.mean(axis=0)
#broadcast vector three times because trailing dimension match 

print(V_nomean.std(axis=0))

V_std = V_nomean / V_nomean.std(axis=0)



(3, 4)
(4,)
[3.26598632 3.26598632 3.26598632 3.26598632]


array([[-1.22474487, -1.22474487, -1.22474487, -1.22474487],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 1.22474487,  1.22474487,  1.22474487,  1.22474487]])

In [4]:
u3

array([0. , 0.1, 0.2])

In [5]:
# V + u3 
# this fails


In [6]:
u3.reshape((3, 1))

array([[0. ],
       [0.1],
       [0.2]])

In [7]:
V + u3.reshape((3, 1)) # broadcasting u3 horizontally along axis of length 1


array([[ 0. ,  1. ,  2. ,  3. ],
       [ 4.1,  5.1,  6.1,  7.1],
       [ 8.2,  9.2, 10.2, 11.2]])

In [226]:
# Same as copying u3 four times:
np.allclose(
        V + u3.reshape((3, 1)),
        V + np.column_stack([u3, u3, u3, u3]))

# column_stack is short for turning u3 into a (3,1) vector, then hstack

True

In [227]:
np.column_stack([u3, u3, u3, u3])

array([[0. , 0. , 0. , 0. ],
       [0.1, 0.1, 0.1, 0.1],
       [0.2, 0.2, 0.2, 0.2]])

In [228]:
np.hstack([u3.reshape(3,1), u3.reshape(3,1), u3.reshape(3,1), u3.reshape(3,1)])

array([[0. , 0. , 0. , 0. ],
       [0.1, 0.1, 0.1, 0.1],
       [0.2, 0.2, 0.2, 0.2]])

In [229]:
V * u4.reshape((1, 4)) # broadcasting u4 vertically along axis of length 1

array([[0.  , 0.01, 0.04, 0.09],
       [0.  , 0.05, 0.12, 0.21],
       [0.  , 0.09, 0.2 , 0.33]])

In [230]:
V * u4 # this works because trailing dim matches

array([[0.  , 0.01, 0.04, 0.09],
       [0.  , 0.05, 0.12, 0.21],
       [0.  , 0.09, 0.2 , 0.33]])

In [231]:
# Same as the sum of three u4 stacked vertically:
np.allclose(
        V * u4.reshape((1, 4)),
        V * np.stack([u4, u4, u4 ]))

True

In [232]:
# what happens with a 3x3 matrix?
test = np.arange(9).reshape(3,3)
test2 = np.array([1,2,3])
test3 = np.array([6,7,8]).reshape(3,1)

In [233]:
test 

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [234]:
test2

array([1, 2, 3])

In [235]:
test3

array([[6],
       [7],
       [8]])

In [236]:
test + test2 # row vectors with shape (1,3) or (3,) will be added to each row

array([[ 1,  3,  5],
       [ 4,  6,  8],
       [ 7,  9, 11]])

In [237]:
test + test3 # column vectors (3,1) will be added to each column

array([[ 6,  7,  8],
       [10, 11, 12],
       [14, 15, 16]])

More examples

In [238]:
np.random.normal(size=(4, 4)) * np.random.normal(size=(4, 1))

array([[-0.03831005, -0.09974464, -0.48978027, -0.23845806],
       [-0.44937391,  1.03127044,  0.33521515, -1.71992523],
       [-0.15529269,  0.18452151,  0.32436358, -0.29309952],
       [-0.19141432, -0.17290051,  0.15580827,  0.05740805]])

In [239]:
A = np.array(range(2*3*4)).reshape((2,3,4))

In [240]:
B = A * np.array([1, -1, 2, -2]).reshape((1,1,4))

In [241]:
B.shape

(2, 3, 4)

In [242]:
A[:, :, 1]

array([[ 1,  5,  9],
       [13, 17, 21]])

In [243]:
B[:, :, 1]

array([[ -1,  -5,  -9],
       [-13, -17, -21]])

More examples

    A (2d array)      4 x 1
    B (1d array)          3
    Result (2d array) 4 x 3


<img src="https://numpy.org/doc/stable/_images/broadcasting_4.png" width="450" />


this dimension nis replicated to match the other dimension and vis versa 
example: subject level means, feature level means, this is how you would acheive that 

3d array example:

In [244]:
C = np.array(np.arange(5*2)).reshape((5,2))

In [245]:
C

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

<img src="img/Broadcasting.png" width="600" />

In [246]:
out = C[np.newaxis, :, :] + C[:, np.newaxis, :]

    C1      1 x 5 x 2
    C2      5 x 1 x 2
    Result  5 x 5 x 2

In [247]:
out.shape

(5, 5, 2)

In [248]:
out[:, :, 0]

array([[ 0,  2,  4,  6,  8],
       [ 2,  4,  6,  8, 10],
       [ 4,  6,  8, 10, 12],
       [ 6,  8, 10, 12, 14],
       [ 8, 10, 12, 14, 16]])

Multiply many matrices:


In [14]:
S = np.stack([np.random.randn(2, 2) for a in range(5)]).round(2)
S.shape
S

array([[[-1.17,  0.84],
        [-1.4 , -1.66]],

       [[-1.56, -0.06],
        [ 1.04, -0.64]],

       [[-0.53, -0.59],
        [ 0.21,  0.43]],

       [[ 2.81, -0.5 ],
        [ 0.62,  0.82]],

       [[-0.15, -0.28],
        [-0.55,  0.27]]])

Computing inverses of the five matrices one by one

In [ ]:
S.shape
S[0] # look at the first dimension of S which is a 2x2 matrix 
np.linalg.inv(S[3,:,:])

# take the fourth 2x2 matrix in S and compute its inverse
# multi dimension array 

array([[-1.17,  0.84],
       [-1.4 , -1.66]])

In [250]:
S[0]

S[0, :, :]

np.linalg.inv(S[0])

array([[-2.5297619 , -2.23214286],
       [ 1.50669643,  2.06473214]])

With many matrices:

In [17]:
S = np.stack([np.random.randn(2, 2) for a in range(100000)])
S.shape

(100000, 2, 2)

In [ ]:
from timeit import default_timer as timer

#option 1 - more pythonic 
# fast
start = timer()
np.linalg.inv(S)  #take the inverse of every single matrix in S 
end = timer()
print(end - start)

# option 2
# slow, using loop to compute inverse of each 2x2 matrix in S
start = timer()
[np.linalg.inv(mat) for mat in S]  #more compact way to do loop 
end = timer()
print(end - start)

# #option 3
# output = []
# for i in range(S.shape[0]):
#     output.append(np.linalg.inv(S[i, :, :]))

0.010184914999626926
0.35890168999867456


In [20]:
S.shape
print(type(S.shape))
print(type(S))
S.shape[0]

<class 'tuple'>
<class 'numpy.ndarray'>


100000